version: '3'

volumes:
  db_data:

services:
  db:
    image: postgres:12
    volumes:
      - "db_data:/var/lib/posggresql/data"
    environment:
     - 'POSTGRES_USER=postgres'
     - 'POSTGRES_PASSWORD=postgres'

  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product'
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - "DATABASE_PASSWORD=postgres"
    depends_on:
      - db
    links:
      - db